name: Close Sub-Issues

on:
  issues:
    types: [closed]

permissions:
  issues: write      # Required to close issues and add comments
  contents: read     # Required to access repository

jobs:
  close-sub-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close Sub-Issues
        uses: RehabAbotalep/close-sub-issues-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          repository: ${{ github.repository }}
